In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dust.csv', index_col=0)
df.head()

,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,세종,경북,경남,제주,강원.1
날짜,,,,,,,,,,,,,,,,,,
08월 11일,7,17,15,10,29,12,12,9,16,14,16,25,21,11,14,24,21,16
08월 10일,15,25,15,20,28,25,17,20,16,25,29,29,25,27,14,29,23,16
08월 09일,24,26,26,27,27,27,22,27,25,32,24,24,27,26,25,38,25,25
08월 08일,26,25,28,26,29,31,20,26,29,33,26,29,31,31,28,32,27,29
08월 07일,20,26,22,25,33,24,18,23,18,23,29,33,29,27,19,28,26,18

### row가 중복되는 경우

In [3]:
df.index

Index(['08월 11일', '08월 10일', '08월 09일', '08월 08일', '08월 07일', '08월 06일',
       '08월 05일', '08월 04일', '08월 03일', '08월 02일', '08월 01일', '07월 31일',
       '07월 31일', '07월 30일', '07월 29일', '07월 28일', '07월 27일', '07월 26일',
       '07월 25일', '07월 24일', '07월 23일', '07월 22일', '07월 21일', '07월 20일',
       '07월 19일', '07월 18일', '07월 17일', '07월 16일', '07월 15일', '07월 14일',
       '07월 13일'],
      dtype='object', name='날짜')

In [4]:
df.index.value_counts()

07월 31일    2
07월 26일    1
08월 08일    1
08월 07일    1
07월 19일    1
07월 25일    1
08월 02일    1
08월 04일    1
07월 17일    1
07월 29일    1
07월 24일    1
07월 28일    1
07월 27일    1
08월 01일    1
08월 11일    1
08월 09일    1
08월 05일    1
07월 30일    1
07월 13일    1
07월 14일    1
08월 10일    1
07월 18일    1
08월 03일    1
07월 20일    1
07월 21일    1
07월 15일    1
08월 06일    1
07월 16일    1
07월 22일    1
07월 23일    1
Name: 날짜, dtype: int64

In [5]:
df.loc['07월 31일']

,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,세종,경북,경남,제주,강원.1
날짜,,,,,,,,,,,,,,,,,,
07월 31일,18,26,17,23,23,17,23,21,19,20,21,21,22,19,22,25,28,19
07월 31일,18,26,17,23,23,17,23,21,19,20,21,21,22,19,22,25,28,19

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df

,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,세종,경북,경남,제주,강원.1
날짜,,,,,,,,,,,,,,,,,,
08월 11일,7,17,15,10,29,12,12,9,16,14,16,25,21,11,14,24,21,16
08월 10일,15,25,15,20,28,25,17,20,16,25,29,29,25,27,14,29,23,16
08월 09일,24,26,26,27,27,27,22,27,25,32,24,24,27,26,25,38,25,25
08월 08일,26,25,28,26,29,31,20,26,29,33,26,29,31,31,28,32,27,29
08월 07일,20,26,22,25,33,24,18,23,18,23,29,33,29,27,19,28,26,18
08월 06일,31,39,29,35,27,31,31,30,22,33,28,27,30,34,29,37,24,22
08월 05일,27,36,25,31,27,24,30,27,25,31,25,26,25,25,28,31,22,25
08월 04일,27,36,26,31,27,27,32,31,39,36,30,27,27,29,29,36,27,39
08월 03일,44,32,23,47,29,28,29,44,33,31,34,27,28,32,28,31,26,33
08월 02일,40,26,20,41,26,19,20,39,25,24,33,29,22,24,22,27,32,25
08월 01일,33,26,22,40,24,18,26,35,20,26,36,30,23,28,21,25,30,20
07월 31일,18,26,17,23,23,17,23,21,19,20,21,21,22,19,22,25,28,19
07월 30일,10,28,14,15,18,14,24,14,17,15,15,15,18,15,20,22,29,17
07월 29일,18,29,16,22,28,23,30,20,22,26,26,27,27,24,29,25,35,22
07월 28일,39,38,29,41,37,44,30,40,37,50,39,43,42,41,36,46,29,37
07월 27일,48,51,41,39,30,41,57,47,45,52,37,35,37,46,46,55,24,45
07월 26일,41,55,36,39,30,29,60,39,37,37,29,32,27,31,36,47,29,37
07월 25일,32,40,30,31,29,26,46,31,39,35,24,28,24,26,36,35,28,39
07월 24일,42,33,31,37,20,33,44,42,39,49,31,22,21,39,39,30,23,39
07월 23일,31,31,25,28,21,26,33,35,41,37,26,22,22,31,27,30,24,41
07월 22일,30,28,20,30,21,40,26,34,44,48,39,36,22,46,26,29,30,44
07월 21일,37,37,41,30,48,57,42,38,51,59,40,59,43,56,49,43,39,51
07월 20일,36,70,56,27,46,44,77,36,44,51,33,44,54,44,61,68,46,44
07월 19일,30,76,54,29,36,40,81,32,40,47,28,35,39,35,55,66,26,40
07월 18일,35,55,42,36,39,42,66,36,39,47,32,35,35,42,47,53,28,39
07월 17일,30,56,49,32,38,36,65,32,44,43,30,32,43,38,49,55,37,44
07월 16일,26,48,42,24,37,30,59,28,36,38,23,25,34,32,36,47,36,36
07월 15일,22,49,21,22,23,18,55,23,25,24,17,19,22,20,25,41,27,25
07월 14일,20,46,26,22,24,17,54,21,26,23,16,19,20,18,26,39,21,26
07월 13일,21,43,29,19,23,19,47,21,24,24,15,21,21,19,26,38,23,24

### column이 중복된 경우

df.T 하면 row와 column이 바뀜

In [9]:
df.T

날짜,08월 11일,08월 10일,08월 09일,08월 08일,08월 07일,08월 06일,08월 05일,08월 04일,08월 03일,08월 02일,...,07월 22일,07월 21일,07월 20일,07월 19일,07월 18일,07월 17일,07월 16일,07월 15일,07월 14일,07월 13일
서울,7,15,24,26,20,31,27,27,44,40,...,30,37,36,30,35,30,26,22,20,21
부산,17,25,26,25,26,39,36,36,32,26,...,28,37,70,76,55,56,48,49,46,43
대구,15,15,26,28,22,29,25,26,23,20,...,20,41,56,54,42,49,42,21,26,29
인천,10,20,27,26,25,35,31,31,47,41,...,30,30,27,29,36,32,24,22,22,19
광주,29,28,27,29,33,27,27,27,29,26,...,21,48,46,36,39,38,37,23,24,23
대전,12,25,27,31,24,31,24,27,28,19,...,40,57,44,40,42,36,30,18,17,19
울산,12,17,22,20,18,31,30,32,29,20,...,26,42,77,81,66,65,59,55,54,47
경기,9,20,27,26,23,30,27,31,44,39,...,34,38,36,32,36,32,28,23,21,21
강원,16,16,25,29,18,22,25,39,33,25,...,44,51,44,40,39,44,36,25,26,24
충북,14,25,32,33,23,33,31,36,31,24,...,48,59,51,47,47,43,38,24,23,24
충남,16,29,24,26,29,28,25,30,34,33,...,39,40,33,28,32,30,23,17,16,15
전북,25,29,24,29,33,27,26,27,27,29,...,36,59,44,35,35,32,25,19,19,21
전남,21,25,27,31,29,30,25,27,28,22,...,22,43,54,39,35,43,34,22,20,21
세종,11,27,26,31,27,34,25,29,32,24,...,46,56,44,35,42,38,32,20,18,19
경북,14,14,25,28,19,29,28,29,28,22,...,26,49,61,55,47,49,36,25,26,26
경남,24,29,38,32,28,37,31,36,31,27,...,29,43,68,66,53,55,47,41,39,38
제주,21,23,25,27,26,24,22,27,26,32,...,30,39,46,26,28,37,36,27,21,23
강원.1,16,16,25,29,18,22,25,39,33,25,...,44,51,44,40,39,44,36,25,26,24

In [14]:
df = df.T.drop_duplicates().T
df

         서울  부산  대구  인천  광주  대전  울산  경기  강원  충북  충남  전북  전남  세종  경북  경남  제주
날짜
08월 11일   7  17  15  10  29  12  12   9  16  14  16  25  21  11  14  24  21
08월 10일  15  25  15  20  28  25  17  20  16  25  29  29  25  27  14  29  23
08월 09일  24  26  26  27  27  27  22  27  25  32  24  24  27  26  25  38  25
08월 08일  26  25  28  26  29  31  20  26  29  33  26  29  31  31  28  32  27
08월 07일  20  26  22  25  33  24  18  23  18  23  29  33  29  27  19  28  26
08월 06일  31  39  29  35  27  31  31  30  22  33  28  27  30  34  29  37  24
08월 05일  27  36  25  31  27  24  30  27  25  31  25  26  25  25  28  31  22
08월 04일  27  36  26  31  27  27  32  31  39  36  30  27  27  29  29  36  27
08월 03일  44  32  23  47  29  28  29  44  33  31  34  27  28  32  28  31  26
08월 02일  40  26  20  41  26  19  20  39  25  24  33  29  22  24  22  27  32
08월 01일  33  26  22  40  24  18  26  35  20  26  36  30  23  28  21  25  30
07월 31일  18  26  17  23  23  17  23  21  19  20  21  21  22  19  22  25  28
07월 30일  10  28  14  15  18  14  24  14  17  15  15  15  18  15  20  22  29
07월 29일  18  29  16  22  28  23  30  20  22  26  26  27  27  24  29  25  35
07월 28일  39  38  29  41  37  44  30  40  37  50  39  43  42  41  36  46  29
07월 27일  48  51  41  39  30  41  57  47  45  52  37  35  37  46  46  55  24
07월 26일  41  55  36  39  30  29  60  39  37  37  29  32  27  31  36  47  29
07월 25일  32  40  30  31  29  26  46  31  39  35  24  28  24  26  36  35  28
07월 24일  42  33  31  37  20  33  44  42  39  49  31  22  21  39  39  30  23
07월 23일  31  31  25  28  21  26  33  35  41  37  26  22  22  31  27  30  24
07월 22일  30  28  20  30  21  40  26  34  44  48  39  36  22  46  26  29  30
07월 21일  37  37  41  30  48  57  42  38  51  59  40  59  43  56  49  43  39
07월 20일  36  70  56  27  46  44  77  36  44  51  33  44  54  44  61  68  46
07월 19일  30  76  54  29  36  40  81  32  40  47  28  35  39  35  55  66  26
07월 18일  35  55  42  36  39  42  66  36  39  47  32  35  35  42  47  53  28
07월 17일  30  56  49  32  38  36  65  32  44  43  30  32  43  38  49  55  37
07월 16일  26  48  42  24  37  30  59  28  36  38  23  25  34  32  36  47  36
07월 15일  22  49  21  22  23  18  55  23  25  24  17  19  22  20  25  41  27
07월 14일  20  46  26  22  24  17  54  21  26  23  16  19  20  18  26  39  21
07월 13일  21  43  29  19  23  19  47  21  24  24  15  21  21  19  26  38  23